### ISSUE TITLE
Feature request: Add K / D to UI

### ISSUE THREAD

**Issue by dcieslak19973** [kuschAoe/AoE4_ObserverUI#2]
Even better would be to break down K / D based on military or economic units.

**Comment by kuschAoe** [comment]
tldr; Deaths, will do. Kills, no.

Deaths will be no problem, in fact the backend of the Overlay used since N4C already tracks them it just never made it onto the UI.

Kills however are not reliably attributable to players due to for instance kills by AoE attacks like mangonels/demos/... therefore there'd always be a discrepancy between kills and deaths and while some discrepency is correct e.g. due to deleting your own units or kills by gaia units the discrepency caused by AoE attacks of player units is just plain and simple wrong.

**Comment by dcieslak19973** [comment]
Would it be possible to differentiate economic deaths from military deaths?

**Comment by kuschAoe** [comment]
Yes!
